# Generated by Django 2.1.7 on 2019-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='date published')),
                ('Tracking', models.CharField(max_length=200)),
                ('String_Value', models.CharField(max_length=200)),
                ('Numerical_Value', models.CharField(max_length=200)),
                ('Additional_Information', models.CharField(max_length=200)),
            ],
        ),
    ]
