# Generated by Django 2.1.7 on 2019-02-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190224_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='Source',
            field=models.CharField(blank=True, default='Manual', max_length=200, null=True),
        ),
    ]
