# Generated by Django 2.1.7 on 2020-02-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200221_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='author',
            new_name='Username',
        ),
    ]
