# Generated by Django 2.1.7 on 2020-02-22 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200221_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entries',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
