# Generated by Django 2.2.10 on 2020-02-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20200222_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.CharField(default=180, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.CharField(default=60, max_length=100),
            preserve_default=False,
        ),
    ]
