# Generated by Django 2.2.10 on 2020-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weight_tracker',
            field=models.BooleanField(default=True),
        ),
    ]
