# Generated by Django 2.2.10 on 2020-02-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20200223_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='countdown_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
