# Generated by Django 2.2.10 on 2020-02-27 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_userprofile_countdown_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='countdown_number',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='Nurtrition_Info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.NutritionInfo'),
        ),
    ]
