# Generated by Django 2.2.10 on 2020-03-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20200227_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioninfo',
            name='glycemicindex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritioninfo',
            name='glycemicload',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
