# Generated by Django 2.2.10 on 2020-03-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20200301_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bm_tracker',
            field=models.BooleanField(default=False),
        ),
    ]
